package com.pbs.pbscompanion;

import static android.content.Context.MODE_PRIVATE;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

public class DAO {
    private SQLiteDatabase newsDB;

    public void initializeDB() {
        newsDB = SQLiteDatabase.openOrCreateDatabase("/data/data/com.pbs.pbscompanion/databases/testDB",null);
        newsDB.execSQL("CREATE TABLE IF NOT EXISTS news(id INTEGER PRIMARY KEY AUTOINCREMENT, title VARCHAR NOT NULL, content VARCHAR NOT NULL, department VARCHAR NOT NULL, date VARCHAR NOT NULL);");
        newsDB.execSQL("DELETE FROM news");
        newsDB.execSQL("INSERT INTO news VALUES(null, 'Porozumienie PBŚ z WOT', '21 stycznia 2022 roku JM Rektor prof. Marek Adamski podpisał w imieniu Politechniki Bydgoskiej porozumienie o współpracy z 8. Kujawsko-Pomorską Brygadą Obrony Terytorialnej reprezentowaną przez płk. Krzysztofa Stańczyka. Celem podpisanego porozumienia jest między innymi upowszechnianie działalności edukacyjnej na rzecz obronności państwa, kształtowanie pozytywnego wizerunku Wojsk Obrony Terytorialnej, upowszechnianie tradycji oraz promocji osiągnięć Brygady i Politechniki, kształtowanie wśród studentów Politechniki postaw patriotycznych czy prowadzenie działań promocyjno-informacyjnych dotyczących popularyzacji służby wojskowej i postaw proobronnych. 8. Kujawsko-Pomorska Brygada Obrony Terytorialnej im. gen. Elżbiety Zawackiej, ps. „Zo” opiera swój potencjał na żołnierzach-ochotnikach, którzy dzięki terytorialnemu charakterowi formacji mają możliwość pełnienia służby w obszarze swojego zamieszkania. O przyjęcie w szeregi Wojsk Obrony Terytorialnej mogą ubiegać się rezerwiści, a także te osoby, które do tej pory nie pełniły żadnej formy służby wojskowej.  Dzięki temu, że szkolenia odbywają się głównie w dni wolne od pracy - służba w WOT daje możliwość pogodzenia życia rodzinnego i zawodowego ze służbą Ojczyźnie. 8. Kujawsko-Pomorska Brygada Obrony Terytorialnej powstała 15 stycznia 2018 roku i liczy obecnie ponad 2000 żołnierzy. Od początku jej istnienia Dowódcą jest płk Krzysztof Stańczyk. W jej strukturze są 3 bataliony znajdujące się w Toruniu, Inowrocławiu i Grudziądzu. Ruszyły prace nad utworzeniem 4 batalionu we Włocławku. Żołnierze wspierają lokalną społeczność w przeciwdziałaniu skutkom pandemii wirusa SARS-CoV-2. Od początku kryzysu migracyjnego wspierają również Straż Graniczną w monitorowaniu i zabezpieczaniu granicy z Białorusią.', 'PBS', '2022-01-21')");
        newsDB.execSQL("INSERT INTO news VALUES(null, 'Nowy prodziekan Wydziału Inżynierii Mechanicznej', '24 stycznia 2022 roku stanowisko Prodziekana ds. kształcenia i spraw studenckich na Wydziale Inżynierii Mechanicznej objęła dr inż. Patrycja Bałdowska-Witos. Życzymy powodzenia na nowym stanowisku oraz samych sukcesów. Dr inż. Patrycja Bałdowska-Witos prowadzi analizy i badania naukowe w zakresie celowego sterowania procesami przetwórczymi i cechami materiałowymi tworzyw polimerowych zmierzającymi do skutecznego ich kształtowania, a w konsekwencji, minimalizowania ich szkodliwego wpływu na środowisko. W efekcie dotychczasowych działań i dociekań naukowych w październiku 2019 r. uzyskała tytuł naukowy doktora nauk technicznych w dyscyplinie inżynieria mechaniczna. W latach 2019-2021 z problematyki zainteresowań naukowych opublikowała ponad 50 publikacji, z czego ponad 20 w periodykach naukowych z listy MNiSW. W roku 2020 ukazała się monografia naukowa pt. „Ekoefektywność procesu formowania opakowań”. Obecnie pełni funkcję Członka Rady Naukowej Dyscypliny Inżynieria Mechaniczna, członka Bydgoskiego Towarzystwa Naukowego oraz od roku 2020 redaktora naczelnego czasopisma naukowego „Ekologia i Technika”. Od 2021 r. sprawuje również opiekę nad promocją i rozwojem Koła Naukowego Eko-Technik działającego na Wydziale Inżynierii Mechanicznej Politechniki Bydgoskiej.', 'PBS', '2022-01-24')");
        newsDB.execSQL("INSERT INTO news VALUES(null, 'Politechnika Bydgoska gra z WOŚP!', 'Politechnika Bydgoska drugi rok z rzędu wspiera Wielką Orkiestrę Świątecznej Pomocy, która w tym roku gra pod hasłem \"Przejrzyj na oczy\". 30. Finał odbędzie się w najbliższą niedzielę, 30 stycznia 2022 r. Swoją twórczością podzielili się wykładowcy Wydziału Sztuk Projektowych, który dołączył do dotychczasowych struktur bydgoskiej uczelni wraz z początkiem roku. Można będzie wylicytować między innymi fotografię autorstwa Dziekana Wydziału, liczne obrazy, grafiki, rzeźbę, a dla pań uczelnia przygotowała coś specjalnego - designerską torebkę wykonaną przez zdobywczynię \"Złotej Pętelki 2021\", znaną z \"Project Runway\", Sarę Betkier. Licytować można do 14 lutego! #PomaganieJestFajne, a w tym przypadku może być też piękne i inspirujące. Nie zwlekajcie i grajcie razem z nami dla #WOŚP. Odwiedzajcie też naszą uczelnianą eSKARBONKĘ.', 'PBS', '2022-01-26')");
        newsDB.execSQL("INSERT INTO news VALUES(null, 'ZDALNY tryb kształcenia', 'Liczba zakażeń koronawirusem na Politechnice Bydgoskiej stanowi obecnie niespełna 1% wśród wszystkich studentów i pracowników. Biorąc jednak pod uwagę niepokojące prognozy dotyczące rozwoju pandemii w kraju oraz prośby kierowane przez członków społeczności akademickiej, władze Uczelni podjęły decyzję o wprowadzeniu zdalnego trybu kształcenia. Zgodnie z Zarządzeniem JM Rektora, nauka zdalna na studiach stacjonarnych I, II i III stopnia oraz dla doktorantów Szkoły Doktorskiej obowiązuje od 31 stycznia 2022 roku do 20 lutego 2022 roku. W przypadku studiów niestacjonarnych I i II stopnia kształcenie zdalne odbywa się od 28 stycznia 2022 roku do 20 lutego 2022 roku. ', 'PBS', '2022-01-26')");
        newsDB.execSQL("INSERT INTO news VALUES(null, 'Koncert \"Hej, Kolęda!\"', 'Zachęcamy wszystkich do wspólnego kolędowania wraz z Chórem Akademickim Politechniki Bydgoskiej pod batutą dr Agnieszki Sowy. Koncert \"Hej, Kolęda!\" odbędzie się 15 stycznia 2022 roku w kościele p.w. Św. Krzyża w Bydgoszczy (ul. Artyleryjska). Zaczynamy o godzinie 14:00.', 'WTIE', '2022-01-12')");
        newsDB.execSQL("INSERT INTO news VALUES(null, 'Politechnika Bydgoska gra z WOŚP!', 'Politechnika Bydgoska drugi rok z rzędu wspiera Wielką Orkiestrę Świątecznej Pomocy, która w tym roku gra pod hasłem \"Przejrzyj na oczy\". 30. Finał odbędzie się w najbliższą niedzielę, 30 stycznia 2022 r. Swoją twórczością podzielili się wykładowcy Wydziału Sztuk Projektowych, który dołączył do dotychczasowych struktur bydgoskiej uczelni wraz z początkiem roku. Można będzie wylicytować między innymi fotografię autorstwa Dziekana Wydziału, liczne obrazy, grafiki, rzeźbę, a dla pań uczelnia przygotowała coś specjalnego - designerską torebkę wykonaną przez zdobywczynię \"Złotej Pętelki 2021\", znaną z \"Project Runway\", Sarę Betkier. Licytować można do 14 lutego! #PomaganieJestFajne, a w tym przypadku może być też piękne i inspirujące. Nie zwlekajcie i grajcie razem z nami dla #WOŚP. Odwiedzajcie też naszą uczelnianą eSKARBONKĘ.', 'WTIE', '2022-01-26')");
        newsDB.execSQL("INSERT INTO news VALUES(null, 'ZDALNY tryb kształcenia', 'Liczba zakażeń koronawirusem na Politechnice Bydgoskiej stanowi obecnie niespełna 1% wśród wszystkich studentów i pracowników. Biorąc jednak pod uwagę niepokojące prognozy dotyczące rozwoju pandemii w kraju oraz prośby kierowane przez członków społeczności akademickiej, władze Uczelni podjęły decyzję o wprowadzeniu zdalnego trybu kształcenia. Zgodnie z Zarządzeniem JM Rektora, nauka zdalna na studiach stacjonarnych I, II i III stopnia oraz dla doktorantów Szkoły Doktorskiej obowiązuje od 31 stycznia 2022 roku do 20 lutego 2022 roku. W przypadku studiów niestacjonarnych I i II stopnia kształcenie zdalne odbywa się od 28 stycznia 2022 roku do 20 lutego 2022 roku. ', 'WTIE', '2022-01-26')");
    }

    public SQLiteDatabase getNewsDB() {
        return newsDB;
    }
}
